=== InsightQATest/ade/ade-assembly/src/main/conf/xml/AdeCoreIntervalV2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--   

 Copyright IBM Corp. 2012, 2016
 This file is part of Anomaly Detection Engine for Linux Logs (ADE).

 ADE is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 ADE is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with ADE.  If not, see <http://www.gnu.org/licenses/>.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.openmainframe.org/ade/AdeCoreIntervalV2"
    xmlns="http://www.openmainframe.org/ade/AdeCoreIntervalV2" elementFormDefault="qualified">
    <xs:element name="interval">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="version" type="xs:int" />
                <xs:element name="sys_id" type="xs:string" />
                <xs:element name="start_time" type="xs:dateTime" />
                <xs:element name="end_time" type="xs:dateTime" />
                <xs:element name="anomaly_score" type="xs:double" />
                <xs:element name="model_internal_id" type="xs:int" />
                <xs:element name="ade_version" type="xs:int" />
                <xs:element name="gmt_offset" type="xs:string" />
                <xs:element name="model_info">
                    <xs:complexType>
                        <xs:attribute name="model_creation_date" type="xs:dateTime" use="required" />
                        <xs:attribute name="training_period" type="xs:int" use="required" />
                        <xs:attribute name="interval_size_in_sec" type="xs:long" use="required" />
                        <xs:attribute name="analysis_group" type="xs:string" use="required" />
                        <xs:attribute name="limited_model" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Yes" />
                                    <xs:enumeration value="No" />
                                    <xs:enumeration value="Unknown" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                    </xs:complexType>
                </xs:element>
                <xs:element name="msg_summary">
                    <xs:complexType>
                        <xs:attribute name="num_new_msg" type="xs:int" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="interval_message" type="interval_message_type" maxOccurs="unbounded"
                    minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="interval_message_type">
        <xs:sequence>
            <xs:element name="num_instances" type="xs:int" />
            <xs:element name="bernoulli">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:double">
                            <xs:attribute name="frequency" type="xs:double" use="required" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="cluster_id" type="xs:int" />
            <xs:element name="periodicity">
                <xs:complexType>
                    <xs:attribute name="status" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="IN_SYNC" />
                                <xs:enumeration value="NOT_IN_SYNC" />
                                <xs:enumeration value="NOT_PERIODIC" />
                                <xs:enumeration value="NEW" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="last_issued" type="xs:dateTime" use="optional" />
                    <xs:attribute name="score" type="xs:double" use="optional" />
                </xs:complexType>
            </xs:element>
            <xs:element name="poisson">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:double">
                            <xs:attribute name="mean" type="xs:double" use="required" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="intCont" type="xs:double" />
            <xs:element name="normIntCont" type="xs:double" />
            <xs:element name="anomaly" type="xs:double" />
            <xs:element name="cluster_status" type="xs:string" />
            <xs:element name="critical_words" type="xs:double" />
            <xs:element name="text_sum" type="xs:string" />
            <xs:element name="text_smp" type="xs:string" />
            <xs:element name="time_vec" type="interval_time_vector_type" />
            <xs:element name="active_rules" type="active_rules_type" maxOccurs="1" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="msg_id" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="interval_time_vector_type">
        <xs:sequence>
            <xs:element name="occ" maxOccurs="unbounded" minOccurs="0" type="xs:int" />
        </xs:sequence>
    </xs:complexType>



    <xs:complexType name="active_rules_type">
        <xs:sequence>
            <xs:element name="rule" type="rule_type" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="rule_type">
        <xs:sequence>
            <xs:element name="name">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="affected_score" type="xs:boolean" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="action" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== InsightQATest/ade/20151212/intervals/interval_8.xml
<?xml version='1.0' encoding='UTF-8' ?> 
<?xml-stylesheet href='./xslt/AdeCoreIntervalV2.xsl' type='text/xsl' ?> 
<interval xsi:noNamespaceSchemaLocation="/xml/AdeCoreIntervalV2.xsd" xmlns="http://www.openmainframe.org/ade/AdeCoreIntervalV2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <version>2</version>
    <sys_id>sys1.openmainframe.org</sys_id>
    <start_time>2015-12-12T00:30:00.000Z</start_time>
    <end_time>2015-12-12T01:30:00.000Z</end_time>
    <anomaly_score>100.0</anomaly_score>
    <model_internal_id>1</model_internal_id>
    <ade_version>321</ade_version>
    <gmt_offset>GMT+00:00</gmt_offset>
    <model_info model_creation_date="2016-02-10T16:02:56.840Z" training_period="7" interval_size_in_sec="3600" analysis_group="default" limited_model="Yes"/>
    <msg_summary num_new_msg="10"/>
    <interval_message msg_id="sshd_47">
        <num_instances>25</num_instances>
        <bernoulli frequency="0.07058823529411765">99.70588235294117</bernoulli>
        <cluster_id>14</cluster_id>
        <periodicity status="NOT_PERIODIC" last_issued="2015-12-12T00:21:00.000Z"/>
        <poisson mean="1.4234978142529124">0.9999910930841008</poisson>
        <intCont>6.986536589037902</intCont>
        <normIntCont>6.986536589037902</normIntCont>
        <anomaly>0.9990757579752175</anomaly>
        <cluster_status>OUT_OF_CONTEXT</cluster_status>
        <critical_words>0.0</critical_words>
        <text_sum>Accepted keyboard-interactive/pam for user1 from 5dbf2b6d08477c5fc7774f590b31abd4f39be38a port * ssh2</text_sum>
        <text_smp>Accepted keyboard-interactive/pam for user1 from 5dbf2b6d08477c5fc7774f590b31abd4f39be38a port 1726 ssh2</text_smp>
        <time_vec>
            <occ>11</occ>
            <occ>12</occ>
            <occ>41</occ>
            <occ>71</occ>
            <occ>90</occ>
            <occ>101</occ>
        </time_vec>
    </interval_message>
    <interval_message msg_id="/usr/sbin/cron(notes):/home/notes/getsysdata.ksh_311">
        <num_instances>4</num_instances>
        <bernoulli frequency="0.07100591715976332">101.0</bernoulli>
        <cluster_id>-1</cluster_id>
        <periodicity status="NOT_PERIODIC" last_issued="2015-12-12T00:15:00.000Z"/>
        <poisson mean="2.0">0.0</poisson>
        <intCont>4.656066344281889</intCont>
        <normIntCont>4.656066344281889</normIntCont>
        <anomaly>0.9904962264578541</anomaly>
        <cluster_status>NEW</cluster_status>
        <critical_words>0.0</critical_words>
        <text_sum>(notes) CMD (/home/notes/getsysdata.ksh 1&gt;/home/notes/run.out 2&gt;&amp;1)</text_sum>
        <text_smp>(notes) CMD (/home/notes/getsysdata.ksh 1&gt;/home/notes/run.out 2&gt;&amp;1)</text_smp>
        <time_vec>
            <occ>0</occ>
            <occ>30</occ>
            <occ>60</occ>
            <occ>90</occ>
        </time_vec>
    </interval_message>
    <interval_message msg_id="/usr/sbin/cron(notesa):/home/notes/getdomdata.ksh_309">
        <num_instances>4</num_instances>
        <bernoulli frequency="0.07100591715976332">101.0</bernoulli>
        <cluster_id>-1</cluster_id>
        <periodicity status="NOT_PERIODIC" last_issued="2015-12-12T00:15:00.000Z"/>
        <poisson mean="2.0">0.0</poisson>
        <intCont>4.656066344281889</intCont>
        <normIntCont>4.656066344281889</normIntCont>
        <anomaly>0.9904962264578541</anomaly>
        <cluster_status>NEW</cluster_status>
        <critical_words>0.0</critical_words>
        <text_sum>(notesa) CMD (/home/notes/getdomdata.ksh 1&gt;~/doms.out 2&gt;&amp;1)</text_sum>
        <text_smp>(notesa) CMD (/home/notes/getdomdata.ksh 1&gt;~/doms.out 2&gt;&amp;1)</text_smp>
        <time_vec>
            <occ>0</occ>
            <occ>30</occ>
            <occ>60</occ>
            <occ>90</occ>
        </time_vec>
    </interval_message>
    <interval_message msg_id="/usr/sbin/cron(notesb):/home/notes/getdomdata.ksh_312">
        <num_instances>4</num_instances>
        <bernoulli frequency="0.07100591715976332">101.0</bernoulli>
        <cluster_id>-1</cluster_id>
        <periodicity status="NOT_PERIODIC" last_issued="2015-12-12T00:15:00.000Z"/>
        <poisson mean="2.0">0.0</poisson>
        <intCont>4.656066344281889</intCont>
        <normIntCont>4.656066344281889</normIntCont>
        <anomaly>0.9904962264578541</anomaly>
        <cluster_status>NEW</cluster_status>
        <critical_words>0.0</critical_words>
        <text_sum>(notesb) CMD (/home/notes/getdomdata.ksh 1&gt;~/doms.out 2&gt;&amp;1)</text_sum>
        <text_smp>(notesb) CMD (/home/notes/getdomdata.ksh 1&gt;~/doms.out 2&gt;&amp;1)</text_smp>
        <time_vec>
            <occ>0</occ>
            <occ>30</occ>
            <occ>60</occ>
            <occ>90</occ>
        </time_vec>
    </interval_message>
    <interval_message msg_id="kernel_280">
        <num_instances>7</num_instances>
        <bernoulli frequency="0.07100591715976332">101.0</bernoulli>
        <cluster_id>-1</cluster_id>
        <periodicity status="NOT_PERIODIC" last_issued="2015-12-11T22:14:00.000Z"/>
        <poisson mean="2.0">0.0</poisson>
        <intCont>4.656066344281889</intCont>
        <normIntCont>4.656066344281889</normIntCont>
        <anomaly>0.9904962264578541</anomaly>
        <cluster_status>NEW</cluster_status>
        <critical_words>0.0</critical_words>
        <text_sum>TCP: Possible SYN flooding on port 1352. Sending cookies.</text_sum>
        <text_smp>TCP: Possible SYN flooding on port 1352. Sending cookies.</text_smp>
        <time_vec>
            <occ>67</occ>
        </time_vec>
    </interval_message>
    <interval_message msg_id="kernel_286">
        <num_instances>1</num_instances>
        <bernoulli frequency="0.07100591715976332">101.0</bernoulli>
        <cluster_id>-1</cluster_id>
        <periodicity status="NOT_PERIODIC" last_issued="2015-12-11T21:16:00.000Z"/>
        <poisson mean="2.0">0.0</poisson>
        <intCont>4.656066344281889</intCont>
        <normIntCont>4.656066344281889</normIntCont>
        <anomaly>0.9904962264578541</anomaly>
        <cluster_status>NEW</cluster_status>
        <critical_words>0.0</critical_words>
        <text_sum>net_ratelimit: 4 callbacks suppressed</text_sum>
        <text_smp>net_ratelimit: 4 callbacks suppressed</text_smp>
        <time_vec>
            <occ>67</occ>
        </time_vec>
    </interval_message>
    <interval_message msg_id="postfix/scache_284">
        <num_instances>2</num_instances>
        <bernoulli frequency="0.07100591715976332">101.0</bernoulli>
        <cluster_id>-1</cluster_id>
        <periodicity status="NOT_PERIODIC" last_issued="2015-12-11T21:31:30.000Z"/>
        <poisson mean="2.0">0.0</poisson>
        <intCont>4.656066344281889</intCont>
        <normIntCont>4.656066344281889</normIntCont>
        <anomaly>0.9904962264578541</anomaly>
        <cluster_status>NEW</cluster_status>
        <critical_words>0.0</critical_words>
        <text_sum>statistics: * lookup hits=0 miss=* success=0%</text_sum>
        <text_smp>statistics: domain lookup hits=0 miss=1 success=0%</text_smp>
        <time_vec>
            <occ>36</occ>
        </time_vec>
    </interval_message>
    <interval_message msg_id="postfix/scache_285">
        <num_instances>1</num_instances>
        <bernoulli frequency="0.07100591715976332">101.0</bernoulli>
        <cluster_id>-1</cluster_id>
        <periodicity status="NOT_PERIODIC" last_issued="2015-12-11T21:31:30.000Z"/>
        <poisson mean="2.0">0.0</poisson>
        <intCont>4.656066344281889</intCont>
        <normIntCont>4.656066344281889</normIntCont>
        <anomaly>0.9904962264578541</anomaly>
        <cluster_status>NEW</cluster_status>
        <critical_words>0.0</critical_words>
        <text_sum>statistics: max simultaneous domains=1 addresses=1 connection=1</text_sum>
        <text_smp>statistics: max simultaneous domains=1 addresses=1 connection=1</text_smp>
        <time_vec>
            <occ>36</occ>
        </time_vec>
    </interval_message>
    <interval_message msg_id="postfix/scache_289">
        <num_instances>1</num_instances>
        <bernoulli frequency="0.07100591715976332">101.0</bernoulli>
        <cluster_id>-1</cluster_id>
        <periodicity status="NOT_PERIODIC" last_issued="2015-12-11T04:48:00.000Z"/>
        <poisson mean="2.0">0.0</poisson>
        <intCont>4.656066344281889</intCont>
        <normIntCont>4.656066344281889</normIntCont>
        <anomaly>0.9904962264578541</anomaly>
        <cluster_status>NEW</cluster_status>
        <critical_words>0.0</critical_words>
        <text_sum>statistics: start interval Dec 12 00:45:01</text_sum>
        <text_smp>statistics: start interval Dec 12 00:45:01</text_smp>
        <time_vec>
            <occ>36</occ>
        </time_vec>
    </interval_message>
    <interval_message msg_id="sshd_281">
        <num_instances>25</num_instances>
        <bernoulli frequency="0.07100591715976332">101.0</bernoulli>
        <cluster_id>-1</cluster_id>
        <periodicity status="NOT_PERIODIC" last_issued="2015-12-12T00:21:00.000Z"/>
        <poisson mean="2.0">0.0</poisson>
        <intCont>4.656066344281889</intCont>
        <normIntCont>4.656066344281889</normIntCont>
        <anomaly>0.9904962264578541</anomaly>
        <cluster_status>NEW</cluster_status>
        <critical_words>0.0</critical_words>
        <text_sum>subsystem request for sftp by user user1</text_sum>
        <text_smp>subsystem request for sftp by user user1</text_smp>
        <time_vec>
            <occ>11</occ>
            <occ>12</occ>
            <occ>41</occ>
            <occ>71</occ>
            <occ>90</occ>
            <occ>101</occ>
        </time_vec>
    </interval_message>
    <interval_message msg_id="syslog-ng_279">
        <num_instances>1</num_instances>
        <bernoulli frequency="0.07100591715976332">101.0</bernoulli>
        <cluster_id>-1</cluster_id>
        <periodicity status="NOT_PERIODIC" last_issued="2015-12-11T23:45:00.000Z"/>
