=== InsightQATest/ade/ade-assembly/src/main/conf/xml/AnalyzedInterval.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 
 Copyright IBM Corp. 2010, 2016
 This file is part of Anomaly Detection Engine for Linux Logs (ADE).

 ADE is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 ADE is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with ADE.  If not, see <http://www.gnu.org/licenses/>.

-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<!--xmlns:ai="http://www.openmainframe.org/AnalyzedInterval" >
	targetNamespace="http://www.openmainframe.org/AnalyzedInterval"
	elementFormDefault="qualified" attributeFormDefault="qualified"-->

	<xsd:element name="AnalyzedInterval"
		type="AnalyzedIntervalType">
	</xsd:element>
	
	<xsd:complexType name="AnalyzedIntervalType">
	
			<xsd:sequence>
				<xsd:element name="Source" type="xsd:string"
					maxOccurs="1" minOccurs="1" />
				<xsd:element name="StartTime" type="xsd:dateTime"
					maxOccurs="1" minOccurs="1" />
            <xsd:element name="StartTimeUnix" type="xsd:long" maxOccurs="1" minOccurs="1"></xsd:element>
            <xsd:element name="EndTime" type="xsd:dateTime"
					maxOccurs="1" minOccurs="1" />
            <xsd:element name="EndTimeUnix" type="xsd:long" maxOccurs="1" minOccurs="1"></xsd:element>
            <xsd:element name="AnomalyScore" type="xsd:double"
					maxOccurs="1" minOccurs="1" />
				<xsd:element name="ModelId" type="xsd:int" maxOccurs="1"
					minOccurs="1" />
				<xsd:element name="AdeVersion" type="xsd:int"
					maxOccurs="1" minOccurs="1" />
				<xsd:element name="AnalyzedMessageSummary"
					type="AnalyzedMessageSummaryType" maxOccurs="unbounded"
					minOccurs="0" />
				<xsd:element name="ScoreSet" type="ScoreSetType"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
			</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="AnalyzedMessageSummaryType">
		<xsd:sequence>
			<xsd:element name="NumOccurrences" type="xsd:int"
				maxOccurs="1" minOccurs="1" />
			<xsd:element name="AnomalyScore" type="xsd:double"
				maxOccurs="1" minOccurs="1"></xsd:element>
			<xsd:element name="ScoreSet" type="ScoreSetType"
				maxOccurs="1" minOccurs="0"></xsd:element>

			<xsd:element name="SummarizedText" type="xsd:string"
				maxOccurs="1" minOccurs="1" />
			<xsd:element name="TextSample" type="xsd:string"
				maxOccurs="1" minOccurs="1" />
			<xsd:element name="ActiveRules" type="ActiveRulesType"
				maxOccurs="1" minOccurs="0" />
			<xsd:element name="TimeLine" type="TimeLineType"
				maxOccurs="1" minOccurs="1" />
			<xsd:any maxOccurs="unbounded" minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute name="MsgId" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="TimeLineType">
		<xsd:sequence>
			<xsd:element name="Occurrence" maxOccurs="unbounded"
				minOccurs="0" type="xsd:float" />
		</xsd:sequence>
	</xsd:complexType>



	<xsd:complexType name="ActiveRulesType">
		<xsd:sequence>
			<xsd:element name="Rule" type="RuleType" maxOccurs="unbounded"
				minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="RuleType">
		<xsd:sequence>
			<xsd:element name="Name" type="xsd:string" />
			<xsd:element name="Action" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="ScoreType">
		<xsd:sequence>
			<xsd:element name="DependsOn" type="ScoreSetType"
				maxOccurs="1" minOccurs="0">
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="ScoreName" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="Score" type="xsd:double"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="ScoreAttributeType">
		<xsd:sequence>
			<xsd:element name="DependsOn" type="ScoreSetType"
				maxOccurs="1" minOccurs="0">
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="ScoreAttributeName" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="Value" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="ScoreSetType">
		<xsd:sequence>
			<xsd:element ref="Score" maxOccurs="unbounded" minOccurs="0"></xsd:element>
			<xsd:element ref="Attribute" maxOccurs="unbounded"
				minOccurs="0"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="Score" type="ScoreType"></xsd:element>
	<xsd:element name="Attribute" type="ScoreAttributeType"></xsd:element>

</xsd:schema>

=== InsightQATest/ade/20151212/intervals/interval_68_debug.xml
<?xml version='1.0' encoding='UTF-8' ?> 
<?xml-stylesheet href='./xslt/AnalyzedInterval.xsl' type="text/xsl" ?> 
<AnalyzedInterval xsi:noNamespaceSchemaLocation="xslt/AnalyzedInterval.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Source>sys1.openmainframe.org</Source>
    <StartTime>2015-12-12T10:30:00.000Z</StartTime>
    <StartTimeUnix>1449916200000</StartTimeUnix>
    <EndTime>2015-12-12T11:30:00.000Z</EndTime>
    <EndTimeUnix>1449919800000</EndTimeUnix>
    <AnomalyScore>0.995</AnomalyScore>
    <ModelId>1</ModelId>
    <AdeVersion>321</AdeVersion>
    <AnalyzedMessageSummary MsgId="sshd_47">
        <NumOccurrences>24</NumOccurrences>
        <AnomalyScore>0.9990129101373006</AnomalyScore>
        <ScoreSet>
            <Score ScoreName="AdeWeightedMessageAnomalyScorerLogNormal.anomaly" Score="0.9990129101373006"/>
            <Score ScoreName="AdeWeightedMessageAnomalyScorerLogNormal.logProb" Score="6.920749476374009"/>
            <Score ScoreName="AdeWeightedMessageAnomalyScorerLogNormal.main" Score="0.9990129101373006"/>
            <Score ScoreName="BestOfTwoScorer.anomaly" Score="0.9970501474926253"/>
            <Score ScoreName="BestOfTwoScorer.logProb" Score="5.82600010738045"/>
            <Score ScoreName="BestOfTwoScorer.main" Score="0.002949852507374632"/>
            <Score ScoreName="ClusteringContextScore.clusterId" Score="14.0"/>
            <Score ScoreName="ClusteringContextScore.main" Score="1.0"/>
            <Score ScoreName="CriticalWordCountReporter.logProb" Score="0.0"/>
            <Score ScoreName="CriticalWordCountReporter.main" Score="0.0"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.frequency" Score="340.0"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.logProb" Score="5.82600010738045"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.main" Score="0.9970501474926253"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.probability" Score="0.0029498525073746312"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.rawAnomaly" Score="0.9970588235294118"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.rawLogProb" Score="5.8289456176102075"/>
            <Score ScoreName="LastSeenLoggingScorerContinuous.anomaly" Score="0.0"/>
            <Score ScoreName="LastSeenLoggingScorerContinuous.logProb" Score="0.0"/>
            <Score ScoreName="LastSeenScorer.anomaly" Score="0.0"/>
            <Score ScoreName="LastSeenScorer.logProb" Score="0.0"/>
            <Score ScoreName="LastSeenScorer.main" Score="1.0"/>
            <Score ScoreName="LogNormalScore.isNew" Score="0.0"/>
            <Score ScoreName="LogNormalScore.logProb" Score="11.299746952348249"/>
            <Score ScoreName="LogNormalScore.main" Score="0.9999876239444027"/>
            <Score ScoreName="LogNormalScore.mean" Score="1.4234978142529124"/>
            <Score ScoreName="SeverityScore.main" Score="1.0"/>
            <Score ScoreName="anomaly" Score="0.9990129101373006"/>
            <Score ScoreName="logProb" Score="6.920749476374009"/>
            <Attribute ScoreAttributeName="BestOfTwoScorer.used" Value="FullBernoulliClusterAwareScore.logProb"/>
            <Attribute ScoreAttributeName="ClusteringContextScore.status" Value="OUT_OF_CONTEXT"/>
            <Attribute ScoreAttributeName="LastSeenLoggingScorerContinuous.LastTime" Value="2015-12-12T10:20:30.000Z"/>
            <Attribute ScoreAttributeName="LastSeenLoggingScorerContinuous.main" Value="regular"/>
            <Attribute ScoreAttributeName="LastSeenLoggingScorerContinuous.res" Value="[900, 900, 30, 870, 30, 870, 30]"/>
        </ScoreSet>
        <SummarizedText>Accepted keyboard-interactive/pam for user1 from 5dbf2b6d08477c5fc7774f590b31abd4f39be38a port * ssh2</SummarizedText>
        <TextSample>Accepted keyboard-interactive/pam for user1 from 5dbf2b6d08477c5fc7774f590b31abd4f39be38a port 3658 ssh2</TextSample>
        <TimeLine>
            <Occurrence>0.09166667</Occurrence>
            <Occurrence>0.34166667</Occurrence>
            <Occurrence>0.35</Occurrence>
            <Occurrence>0.59166664</Occurrence>
            <Occurrence>0.6</Occurrence>
            <Occurrence>0.84166664</Occurrence>
            <Occurrence>0.85</Occurrence>
        </TimeLine>
    </AnalyzedMessageSummary>
    <AnalyzedMessageSummary MsgId="/usr/sbin/cron(notes):/home/notes/getsysdata.ksh_311">
        <NumOccurrences>4</NumOccurrences>
        <AnomalyScore>0.9904962264578541</AnomalyScore>
        <ScoreSet>
            <Score ScoreName="AdeWeightedMessageAnomalyScorerLogNormal.anomaly" Score="0.9904962264578541"/>
            <Score ScoreName="AdeWeightedMessageAnomalyScorerLogNormal.logProb" Score="4.656066344281889"/>
            <Score ScoreName="AdeWeightedMessageAnomalyScorerLogNormal.main" Score="0.9904962264578541"/>
            <Score ScoreName="BestOfTwoScorer.anomaly" Score="0.9970326409495549"/>
            <Score ScoreName="BestOfTwoScorer.logProb" Score="5.820082930352362"/>
            <Score ScoreName="BestOfTwoScorer.main" Score="0.0029673590504451044"/>
            <Score ScoreName="ClusteringContextScore.clusterId" Score="-1.0"/>
            <Score ScoreName="ClusteringContextScore.main" Score="1.0"/>
            <Score ScoreName="CriticalWordCountReporter.logProb" Score="0.0"/>
            <Score ScoreName="CriticalWordCountReporter.main" Score="0.0"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.frequency" Score="338.0"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.logProb" Score="5.820082930352362"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.main" Score="1.0"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.probability" Score="0.002967359050445104"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.rawAnomaly" Score="0.9970414201183432"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.rawLogProb" Score="5.823045895483019"/>
            <Score ScoreName="LastSeenLoggingScorerContinuous.anomaly" Score="0.0"/>
            <Score ScoreName="LastSeenLoggingScorerContinuous.logProb" Score="0.0"/>
            <Score ScoreName="LastSeenScorer.anomaly" Score="0.0"/>
            <Score ScoreName="LastSeenScorer.logProb" Score="0.0"/>
            <Score ScoreName="LastSeenScorer.main" Score="1.0"/>
            <Score ScoreName="LogNormalScore.isNew" Score="1.0"/>
            <Score ScoreName="LogNormalScore.logProb" Score="-0.0"/>
            <Score ScoreName="LogNormalScore.main" Score="0.0"/>
            <Score ScoreName="LogNormalScore.mean" Score="2.0"/>
            <Score ScoreName="SeverityScore.main" Score="1.0"/>
            <Score ScoreName="anomaly" Score="0.9904962264578541"/>
            <Score ScoreName="logProb" Score="4.656066344281889"/>
            <Attribute ScoreAttributeName="BestOfTwoScorer.used" Value="FullBernoulliClusterAwareScore.logProb"/>
            <Attribute ScoreAttributeName="ClusteringContextScore.status" Value="NEW"/>
            <Attribute ScoreAttributeName="LastSeenLoggingScorerContinuous.LastTime" Value="2015-12-12T10:15:00.000Z"/>
            <Attribute ScoreAttributeName="LastSeenLoggingScorerContinuous.main" Value="regular"/>
            <Attribute ScoreAttributeName="LastSeenLoggingScorerContinuous.res" Value="[900, 900, 900, 900]"/>
        </ScoreSet>
        <SummarizedText>(notes) CMD (/home/notes/getsysdata.ksh 1&gt;/home/notes/run.out 2&gt;&amp;1)</SummarizedText>
        <TextSample>(notes) CMD (/home/notes/getsysdata.ksh 1&gt;/home/notes/run.out 2&gt;&amp;1)</TextSample>
        <TimeLine>
            <Occurrence>0.0</Occurrence>
            <Occurrence>0.25</Occurrence>
            <Occurrence>0.5</Occurrence>
            <Occurrence>0.75</Occurrence>
        </TimeLine>
    </AnalyzedMessageSummary>
    <AnalyzedMessageSummary MsgId="/usr/sbin/cron(notesa):/home/notes/getdomdata.ksh_309">
        <NumOccurrences>4</NumOccurrences>
        <AnomalyScore>0.9904962264578541</AnomalyScore>
        <ScoreSet>
            <Score ScoreName="AdeWeightedMessageAnomalyScorerLogNormal.anomaly" Score="0.9904962264578541"/>
            <Score ScoreName="AdeWeightedMessageAnomalyScorerLogNormal.logProb" Score="4.656066344281889"/>
            <Score ScoreName="AdeWeightedMessageAnomalyScorerLogNormal.main" Score="0.9904962264578541"/>
            <Score ScoreName="BestOfTwoScorer.anomaly" Score="0.9970326409495549"/>
            <Score ScoreName="BestOfTwoScorer.logProb" Score="5.820082930352362"/>
            <Score ScoreName="BestOfTwoScorer.main" Score="0.0029673590504451044"/>
            <Score ScoreName="ClusteringContextScore.clusterId" Score="-1.0"/>
            <Score ScoreName="ClusteringContextScore.main" Score="1.0"/>
            <Score ScoreName="CriticalWordCountReporter.logProb" Score="0.0"/>
            <Score ScoreName="CriticalWordCountReporter.main" Score="0.0"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.frequency" Score="338.0"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.logProb" Score="5.820082930352362"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.main" Score="1.0"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.probability" Score="0.002967359050445104"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.rawAnomaly" Score="0.9970414201183432"/>
            <Score ScoreName="FullBernoulliClusterAwareScore.rawLogProb" Score="5.823045895483019"/>
            <Score ScoreName="LastSeenLoggingScorerContinuous.anomaly" Score="0.0"/>
            <Score ScoreName="LastSeenLoggingScorerContinuous.logProb" Score="0.0"/>
            <Score ScoreName="LastSeenScorer.anomaly" Score="0.0"/>
            <Score ScoreName="LastSeenScorer.logProb" Score="0.0"/>
            <Score ScoreName="LastSeenScorer.main" Score="1.0"/>
            <Score ScoreName="LogNormalScore.isNew" Score="1.0"/>
